export const itemlistPayload = {
    itemCode: "",
    itemCategory: "",
    expireDate: "",
    description: "",
    quantity: "",
    levyAmountA: "",
    levyAmountB: "",
    levyAmountC: "",
    levyAmountD: "",
    levyAmountE: "",
    discountAmount: 0.00,
    batchCode: "",
    unitPrice: "",
    itemSubtotal: "",
    totalVat: "",
    totalLevy: "",
    totalAmount: "",
    alt: '',
    refProQty: '',
}

export const headerPayload = {
    increment: "",
    currency: "",
    exchangeRate: "",
    invoiceNumber: "",
    totalLevy: "",
    userName: "",
    flag: "INVOICE",
    calculationType: "",
    totalVat: "",
    transactionDate: "",
    totalAmount: "",
    voucherAmount: "",
    businessPartnerName: "",
    businessPartnerTin: "",
    saleType: "",
    discountType: "GENERAL",
    discountAmount: "",
    reference: "",
    groupReferenceId: "",
    purchaseOrderReference: "",
    items: [],
    invCusId: "",
    remarks: "",
    status: "",
    delivery: "",
}

export const taxPayload = {
    nhil: 0, 
    getfund: 0, 
    covid: 0, 
    cst: 0, 
    tourism: 0, 
    Subtotal: 0
}
